name: CI/CD Pipeline for Codexray

# -------------------------------------
# Triggers: Run on push to main branch
# -------------------------------------
on:
  push:
    branches:
      - main

# -------------------------------------
# Define Environment Variables
# -------------------------------------
env:
  GHCR_IMAGE: ghcr.io/codifinary/codexray-node-agent:latest
  VERSION: 7.0.1

permissions:
  packages: write # Required for pushing Docker images to GHCR
  contents: write # Required for accessing repository contents

# -------------------------------------
# Job 1: CI - Build, Test, Lint
# -------------------------------------
jobs:
  build:
    name: CI - Build, Test, Lint
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      # Cache Go modules to speed up the build process
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Install Go dependencies
      - name: Install dependencies
        run: go mod download

      # Install systemd development headers
      - name: Install systemd development headers
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev

      # Build the Go project
      - name: Build
        run: go build -o codexray-node-agent .

      # Archive the built binary as an artifact
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: codexray-node-agent
          path: codexray-node-agent

  # -------------------------------------
  # Job 2: Build and Push Docker Image to GHCR
  # -------------------------------------
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to GHCR
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Install systemd development headers
      - name: Install systemd development headers
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev

      # Build the codexray-node-agent Binary
      - name: Build codexray-node-agent Binary
        run: |
          # Build the binary using the provided command.
          # The VERSION environment variable is set above.
          GOARCH=amd64 GOOS=linux CGO_ENABLED=1 go build -mod=readonly -ldflags "-X main.version=$VERSION" -o codexray-node-agent .
          # List the output to verify the binary is created.
          ls -la codexray-node-agent

      # Build Docker Image
      - name: Build Docker Image
        run: docker build -t $GHCR_IMAGE -f Dockerfile .

      # Push Docker Image to GHCR
      - name: Push Docker Image to GHCR
        run: docker push $GHCR_IMAGE

      # Create a GitHub Release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}" # Using the version from the env variable.
          release_name: "Release v${{ env.VERSION }}" # Using the version from the env variable.
          draft: false
          prerelease: false

      # Upload Binary as a Release Asset
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./codexray-node-agent # Path to your binary
          asset_name: codexray-node-agent # Name for the asset in the release
          asset_content_type: application/octet-stream
