name: CI/CD Pipeline for Codexray

# -------------------------------------
# Triggers: Run on push to main branch
# -------------------------------------
on:
  push:
    branches:
      - main

# -------------------------------------
# Define Environment Variables
# -------------------------------------
env:
  GHCR_IMAGE: ghcr.io/codifinary/codexray-node-agent:latest

permissions:
  packages: write    # Required for pushing Docker images to GHCR
  contents: read     # Required for accessing repository contents

# -------------------------------------
# Job 1: CI - Build, Test, Lint
# -------------------------------------
jobs:

# -------------------------------------
# Job 2: Build and Push Docker Image to GHCR
# -------------------------------------
  build-and-push:
    name: Build and Push Docker Image to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to GHCR
      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t $GHCR_IMAGE -f Dockerfile .

      # Push Docker Image to GHCR
      - name: Push Docker Image to GHCR
        run: |
          docker push $GHCR_IMAGE
